
-- Create Barbers Table
create table if not exists public.barbers (
  id bigint generated by default as identity primary key,
  name text not null,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Jacaré
insert into public.barbers (name, avatar_url)
values ('Jacaré', '/logo_jacare.jpg');

-- Grant access
alter table public.barbers enable row level security;
create policy "Allow public read access" on public.barbers for select using (true);
